### ISSUE TITLE
Failed to Connect to Server

### ISSUE THREAD

**Issue by Abhijeetbyte** [shivamkumard107/CurrencyDetection#1]
Hi, 
I download your apk it's really a nice app especially voice navigation feature. 
When I click a picture and submit it,  says ***"Failed to Connect to Server. Please Try Again"***.
Then an entry widget says enter Specific Server IP, first I noticed your uploaded [pictures](assets/AppSS/ipConfig.png) , I try the same ip but still didn't work. And i can't able to find the magical ip anywhere in repo. Please mention it

**Comment by droidbaker** [comment]
Hey @Abhijeetbyte. Sorry I'm way too late to respond here. Its not a ready to use project. The backend of this project is not live. As I mentioned in the docs you first need to install and start the server and the ML model. Code: https://github.com/shivamkumard107/CurrencyDetectServer.

**Comment by Abhijeetbyte** [comment]
Thanks for your clarification 😊 .

I really hope to see it in working. I have a project idea related to it.
